### ISSUE TITLE
Can't write initial configuration as root

### ISSUE THREAD

**Issue by cwilling** [cwilling/hoorex#8]
[root@raymonde:~] # hoorex lame
Traceback (most recent call last):
  File "/usr/bin/hoorex", line 427, in <module>
    main()
  File "/usr/bin/hoorex", line 32, in main
    default_config = load_user_config()
  File "/usr/bin/hoorex", line 372, in load_user_config
    with open(config_file, 'wb') as configfile:
IOError: [Errno 2] No such file or directory: '/root/.config/hoorex/defaults.cfg'

**Comment by cwilling** [comment]
This bug fixed - ready for next release.
It was because we made the assumption that xdg_config_home (also xdg_data_home) already existed. In most cases that is correct but obviously (now) not in some server situations which haven' tyet run any apps which create them. In such cases, we need to create them ourselves.
